### ISSUE TITLE
I acc have a doubt about what does aqhax bypasses

### ISSUE THREAD

**Issue by lybaa** [AquaDev86/AqHax-CSGO#14]
Do u know if it does at any external anticheat software? thx bro love ur work

**Comment by krxdev-kaan** [comment]
Firstly, thank you it means a lot that you like the work :) Secondly, of course, external cheats doesn't spesifically exploit anything unlike internal injectors because they have to bypass the DLL signing first and even after injection they have to be really careful about many things but an internal cheat is much more detectable than an external one if the external is done probably. However, if you can gain access to the game's memory congratulations you have took the first step. Now after you gain control over the game's memory, to stay undetectable, you have to be really careful about which variables you are overwriting on the memory because they could be protected or private variables which are not meant to be changed (then VAC hammer slams because it's pretty much sus). That is why you need to be really careful about offsets and structure sizes because you might overwrite something you don't want to. The other thing to be careful of while making an external cheat undetectable is the usage of CreateRemoteThread. CreateRemoteThread is a dangerous function to use because when functions that are not meant to be called are called it's almost inevitable to be detected. That is actually the reason why this cheat doesn't contain Glove Changer because to make a Glove Changer you have to call a private function in the game to instantiate the new glove model then apply texture on it and I want this cheat to stay as undetectable as possible. So, now that you know what is dangerous and what is not dangerous while making an external cheat, it's time to tell you that I programmed AqHax-CSGO as careful as I can to stay undetectable by not making the mistakes that I told you above.

Disclaimer: I just talked about what VAC looks for in external cheats. Of course some might or might not apply for other Anti-Cheat softwares (e.g. EAC).
