### ISSUE TITLE
Query: Is this completely external hack?

### ISSUE THREAD

**Issue by r0ot7** [AquaDev86/AqHax-CSGO#5]
Hello,

Thank you for your efforts.
I have few queries about things I would like to know before I start using it  :)

1. Does it inject anything in the game process.
2. Does it make any in-game memory changes ?

Briefly I just have a doubt whether this is VAC proof ? :)

**Comment by krxdev-kaan** [comment]
1. Yeah m8, it's fully external. So you don't inject anything.
2. Yeah it makes memory changes since it's not just ESP and Aim, there are many features in it such as Skin and Knife Changer :)

Well this hack has a really weird VAC behaviour. I never got vacced in 2 years (i have 2 hacks which uses the same techniques). But i got Overwatch Banned which only affected CSGO competitive matches and not CS 1.6 or any other VAC games but just to make sure you are safe get yourself a side account and do whatever you want :)

**Comment by krxdev-kaan** [comment]
Btw i answered all of your questions in the hack's About page xD
