### ISSUE TITLE
Knife Changer not working

### ISSUE THREAD

**Issue by gahdamnfr** [AquaDev86/AqHax-CSGO#8]
Hello,

Everytime I select a knife in the knife changer tab and press apply & save, I get a IO Error (0x3) and my knife goes invisible in game any fix?

**Comment by krxdev-kaan** [comment]
Hi, finally got back to this project. I couldn't recreate the issue can you provide more info ? you could try to launch the program in admin mode but it shouldn't be necessary normally.

**Comment by krxdev-kaan** [comment]
Oh, just understood the problem you were having. The "Apply & Save" Thing is only used when a skin preset is entered. So that's why. The issue with knife going invisible is probably due to a stability problem right at the time you opened up this issue because it is not present atm. Closing the issue but you can reopen it anytime if the issue still persists.
